schema_version = "1.0.0"

id = "QuickCatalogs"
version = "1.0.0"
name = "Quick Catalogs ( Asset Browser )"
tagline = "Make Asset Catalogs from selected Collections"

maintainer = "justOniL"

type = "add-on"

website = "https://github.com/justonil/QuickCatalogs"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]